### ISSUE TITLE
range(n) should behave like range(0, n)

### ISSUE THREAD

**Issue by fabiosantoscode** [mcandre/node-range#11]
Currently, calling range(10) yields an empty array.

It should really return the same as range(0, 10), like in python.

My proposed fix is simple:

```
if (arguments.length === 1) {
    stop = start;
    start = 0;
}
```

**Comment by mcandre** [comment]
Good idea, I love how Python's `range()` behaves. Would you like to submit a pull request for this?

**Comment by fabiosantoscode** [comment]
Sure, I'll send a pull request.

I've already updated my port back at sapo/Ink
