### ISSUE TITLE
Why does module export object?

### ISSUE THREAD

**Issue by xgbuils** [mcandre/node-range#14]
Hi!

I don't understand why this module exports and object with property 'range' as a function, instead the function itself. This module provide a range function. Why does not export this function?

https://github.com/mcandre/node-range/blob/master/lib/range.js#L28

Examples of popular npm packages that exports a function:
https://www.npmjs.com/package/glob
https://www.npmjs.com/package/browserify
https://www.npmjs.com/package/through2
 
Thanks!

**Comment by mcandre** [comment]
This was the idiom at the time I started writing this package.

**Comment by xgbuils** [comment]
Could I create a PR that exports range function but preserving the old behaviour?
