### ISSUE TITLE
annoying for's

### ISSUE THREAD

**Issue by xgbuils** [mcandre/node-range#7]
I read the code and is a bit annoying to me that there are two loops `for` [almost identical](https://github.com/mcandre/node-range/blob/8a5688ad28e4366e17cac590ac31e92990a7946c/lib/range.js#L18-26). I think that is possible to reduce to one loop and, thus, reduce the weight of file for front end developers that using browserify.

First I thought this option:
``` javascript
  var x, r = [];
  var cmp  = step > 0 
    ? function (x, b) { return x < b }
    : function (x, b) { return x > b };

  for (x = a; cmp(x,b); x += step) {
    r.push(x);
  }
```
But I put too many repeated characters and not just convinced me.
Then I have this idea:
``` javascript
  var x, r = [];

  for (x = a; (b - x) * step > 0; x += step) {
    r.push(x);
  }
```
But the performance of the loop is not too good because it does extra multiplication and subtraction in each iteration.
I solved in this way:
``` javascript
  var x, r  = [];
  var s     = (b - a) * step;
  var step2 = step * step;
  for (x = a; s > 0; x += step) {
    r.push(x);
    s -= step2
  }
```
If you like any of these solutions I can incorporate a PR.

**Comment by mcandre** [comment]
Thanks for pointing that out.

Yes, I believe the original purpose of the code as it was written, was to handle negative ranges in some fashion. Or was it positive ranges?

If you can demonstrate with unix `time` a more performant way to write this code, that still passes unit tests, a pull request would be much appreciated.

**Comment by xgbuils** [comment]
I researched before publishing issue and positive and negative ranges were maintained but [the change](https://github.com/mcandre/node-range/commit/479a2d527ac2639a9638cdd90313afacd142627a) was made because an infinite loop occurs in some cases.

My three proposals pass unit tests. I remains to check unix times. But in the best-case scenario will have the same performance as now.

**Comment by xgbuils** [comment]
My three proposals passes unit tests and lint.

[1st proposal](https://github.com/xgbuils/node-range/tree/fix-issue-7-1st):
``` bash
$ grunt size
...
range.min.js size is 170 bytes
$ time node examples/performance.js 0 30000000

real	0m2.207s
user	0m1.960s
sys	0m0.244s
```

[2nd proposal](https://github.com/xgbuils/node-range/tree/fix-issue-7-2nd):
``` bash
$ grunt size
...
range.min.js size is 115 bytes
$ time node examples/performance.js 0 30000000

real	0m2.153s
user	0m1.920s
sys	0m0.228s
```

[3rd proposal](https://github.com/xgbuils/node-range/tree/fix-issue-7-3rd):
``` bash
$ grunt size
...
range.min.js size is 130 bytes
$ time node examples/performance.js 0 30000000

real	0m2.172s
user	0m1.884s
sys	0m0.276s
```

[Current code](https://github.com/xgbuils/node-range/tree/master)
``` bash
$ grunt size
...
range.min.js size is 150 bytes
$ time node examples/performance.js 0 30000000

real	0m2.143s
user	0m1.876s
sys	0m0.260s
```

unix time to get performance doesn't seem accurate. Choose the one you like!

**Comment by mcandre** [comment]
You are so dedicated, I love it!

I like proposal 2 the best.
