### ISSUE TITLE
Missing .npmignore file

### ISSUE THREAD

**Issue by xgbuils** [mcandre/node-range#9]
Before publishing package in npm, you should know that exists a [`.npmignore` file](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) to keep unnecessary files out of your package (tests, examples, task runner scripts, etc). Code to use, readme.md, package.json and license are just needed in the package.

It's important to check if package works and doesn't have unnecessary files in local enviroment before  publishing:
``` bash
# in another path outside of node-range directory
$ npm install path/to/local/node-range
# check if package works
$ node
> var range = require('range');
> range.range(0,5);
[0,1,2,3,4]
> 
(^C again to quit)
>
# check if the package does not have unnecessary files.
$ cd node_modules/range/
$ ls -a
.  ..  lib  LICENSE.md  package.json  README.md
```

**Comment by mcandre** [comment]
That's a good point. I'll make a note to myself to start writing `.npmignore` files for my Node.js projects.

Would you like to submit a pull request?

**Comment by mcandre** [comment]
Merged https://github.com/mcandre/node-range/pull/10 .

**Comment by mcandre** [comment]
Would you mind submitting similar pull requests for other npm packages?

https://www.npmjs.com/~mcandre

**Comment by mcandre** [comment]
Nevermind, I found some time to do this. :)

**Comment by xgbuils** [comment]
Oh! great! ;-)
